[general]
library_name = "libcimgui"

output_ignorelist = [
    "API",
    "EXTERN",
    "CIMGUI_API",
    "CONST",
    "CIMGUI_INCLUDED",
]

[codegen]
field_access_method_list = [
    "ImGuiIO",
    "ImDrawList",
    "ImDrawData",
    "ImDrawCmd",
    "ImFontAtlas",
    "ImTextureData",
    "ImGuiSizeCallbackData",
    "ImFontConfig",
    "ImGuiPlatformIO",
    "ImGuiViewport",
    "ImVec2_c",
    "ImVec4_c",
    "ImGuiPlatformMonitor",
    "ImGuiStyle",
    "ImGuiListClipper",

    "ImNodesStyle"
]
wrap_variadic_function = true
